version: '3'

services:
  curious-ape:
    container_name: curious-ape
    image: danielcosme/curious-ape
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
    ports:
      - 4000:4000
    volumes:
      - ./config.json:/app/config.json
      - db-data:/app/db-data
    environment:
      - APE_ENVIRONMENT=prod
      - APE_PORT=4000
    depends_on:
      migrate-ape:
        condition: service_completed_successfully

  migrate-ape:
    container_name: migrate-ape
    image: danielcosme/migrate-ape
    volumes:
      - db-data:/db-data
    depends_on:
      restore-ape:
        condition: service_completed_successfully
    entrypoint: ["migrate", "-path" , "/migrations", "-database", "sqlite3:///db-data/ape.db", up]
  
  replicate-ape:
    container_name: replicate-ape
    image: litestream/litestream
    volumes:
      - ./litestream.yml:/etc/litestream.yml
      - db-data:/db-data
    depends_on:
      restore-ape:
        condition: service_completed_successfully
    entrypoint: ["/usr/local/bin/litestream", "replicate"]

  restore-ape:
    container_name: restore-ape
    image: litestream/litestream
    volumes:
      - ./litestream.yml:/etc/litestream.yml
      - db-data:/db-data
    entrypoint: ["litestream", "restore", "-if-db-not-exists", "-if-replica-exists", "/db-data/ape.db"]

volumes:
  db-data:
