# https://taskfile.dev

version: 3

env:
  APE_ENVIRONMENT: dev

vars:
  APP_NAME: ape
  VERSION: v0.18.5

tasks:
  default:
    cmds:
      - task: run

  deploy:
    cmds:
      - task: push
      - ./scripts/release.sh
      - ./scripts/deploy.sh

  push:
    desc: "Push changes to Github creating a new Version"
    deps: [ci]
    cmds:
      - cmd: git diff --exit-code > /dev/null # workig tree cannot be dirty.
      - test {{.CURRENT_BRANCH}} = 'main'
      - task: tag
      - git push
      - git push origin {{.VERSION}}
    vars:
      CURRENT_BRANCH:
        sh: git branch --show-current

  tag:
    cmds:
      - git tag {{.VERSION}}

  version:
    aliases: [v]
    cmds:
      - echo {{.VERSION}}

  run:
    aliases: [r]
    deps: [build]
    cmds:
      - ./tmp/{{.APP_NAME}}

  build:
    aliases: [b]
    cmds:
      - 'go build -ldflags="-X main.version={{.VERSION}}-dev" -o=./tmp/{{.APP_NAME}} ./cmd/web'

  ci:
    deps: [test, audit]

  audit:
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt ./...
      - go vet ./...
      - go tool staticcheck -checks="inherit,-ST1001" ./cmd... ./pkg...

  build-docker:
    env:
      DOCKER_BUILDKIT: 1
    cmds:
      - |
        sudo docker build \
        --build-arg="APE_VERSION={{.VERSION}}" \
        --tag curious-ape \
        --target ape \
        .
      - |
        sudo docker build \
        --tag migrate-ape \
        --target migrate \
        .

  tools:
    desc: "Install CLI tools"
    aliases: [deps]
    cmds:
      - go install github.com/air-verse/air@latest
      - go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go get -tool github.com/rakyll/gotest@latest
      - go get -tool honnef.co/go/tools/cmd/staticcheck@latest
      - go get -tool github.com/stephenafamo/bob/gen/bobgen-sqlite@latest

  test:
    aliases: [t]
    cmds:
      - go tool gotest ./...
  db:
    cmds:
      - "sqlite3 -box ./tmp/{{.APP_NAME}}.db"

  gen-all:
    cmds:
      - task: db-gen-sql

  db-gen-sql:
    deps: [db-migrate-up]
    cmds:
      - go tool bobgen-sqlite -c bobgen.yaml

  db-migrate-new:
    desc: "Generates a new migration file"
    requires:
      vars: [NAME]
    cmds:
      - migrate create -seq -ext=.sql -dir=./database/migrations/sqlite {{.NAME}}

  db-migrate-up:
    cmds:
      - task: db-migrate
        vars:
          OP: up

  db-migrate-down:
    cmds:
      - task: db-migrate
        vars:
          OP: down

  db-migrate-force:
    requires:
      vars: [VERSION]
    cmds:
      - task: db-migrate
        vars:
          OP: force {{.VERSION}}

  db-migrate:
    internal: true
    cmds:
      - migrate -verbose -path "./database/migrations/sqlite" -database "sqlite3://./tmp/{{.APP_NAME}}.db" {{.OP}}
