apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: curious-ape
      labels:
        app: curious-ape
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: curious-ape
      template:
        metadata:
          labels:
            app: curious-ape
        spec:
          nodeSelector:
            kubernetes.io/hostname: ape-1
          initContainers:
            - name: restore-ape
              image: litestream/litestream
              command:
                - litestream
                - restore
                - -if-db-not-exists
                - -if-replica-exists
                - /db-data/ape.db
              volumeMounts:
                - name: db-data
                  mountPath: /db-data
                - name: litestream-config
                  mountPath: /etc/litestream.yml
                  subPath: litestream.yml
            - name: migrate-ape
              image: danielcosme/migrate-ape
              volumeMounts:
                - name: db-data
                  mountPath: /db-data
              command:
                - migrate
                - -path
                - /migrations
                - -database
                - sqlite3:///db-data/ape.db
                - up
          containers:
            - name: curious-ape
              image: danielcosme/curious-ape:latest
              env:
                - name: APE_ENVIRONMENT
                  value: prod
              ports:
                - containerPort: 4000
                  protocol: TCP
              volumeMounts:
                - name: ape-config
                  mountPath: /app/config.json
                  subPath: config.json
                - name: db-data
                  mountPath: /app/db-data
          volumes:
            - name: litestream-config
              configMap:
                name: ape-litestream-prod
                items:
                  - key: litestream.yaml
                    path: litestream.yml
            - name: ape-config
              configMap:
                name: curious-ape-prod
            - name: db-data
              persistentVolumeClaim:
                claimName: curious-ape-pvc
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: curious-ape-backup
      labels:
        app: curious-ape-backup
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: curious-ape-backup
      template:
        metadata:
          labels:
            app: curious-ape-backup
        spec:
          nodeSelector:
            kubernetes.io/hostname: ape-1
          containers:
            - name: replicate-ape
              image: litestream/litestream
              command:
                - litestream
                - replicate
              volumeMounts:
                - name: db-data
                  mountPath: /db-data
                - name: litestream-config
                  mountPath: /etc/litestream.yml
                  subPath: litestream.yml
          volumes:
            - name: litestream-config
              configMap:
                name: ape-litestream-prod
                items:
                  - key: litestream.yaml
                    path: litestream.yml
            - name: db-data
              persistentVolumeClaim:
                claimName: curious-ape-pvc
  - apiVersion: v1
    kind: Service
    metadata:
      name: curious-ape-srv
    spec:
      type: NodePort
      selector:
        app: curious-ape
      ports:
        - nodePort: 30004
          port: 80
          protocol: TCP
          targetPort: 4000
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: curious-ape-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi