apiVersion: batch/v1
kind: Job
metadata:
  name: curious-ape-migrate-down
spec:
  template:
    spec:
      restartPolicy: "Never"
      nodeSelector:
        kubernetes.io/hostname: ape-1
      containers:
        - name: migrate-ape-down
          image: danielcosme/migrate-ape
          command:
            - migrate
            - -path
            - /migrations
            - -database
            - sqlite3:///db-data/ape.db
            - down
            - "1"
          volumeMounts:
            - name: db-data
              mountPath: /db-data
      volumes:
        - name: litestream-config
          configMap:
            name: ape-litestream-prod
            items:
              - key: litestream.yaml
                path: litestream.yml
        - name: db-data
          persistentVolumeClaim:
            claimName: curious-ape-pvc