name: CI Pipeline
on: push

jobs:
  test-and-audit:
    runs-on: daniel-act-runner
    steps:
      - name: Clone Repository
        run: "git clone https://${{ secrets.CI_TOKEN }}@danicos.dev/daniel/curious-ape"

      - name: Install Latest Go
        run: |
          apk add --no-cache git make musl-dev curl tar

          # Install latest Go from official binary (recommended over apk on stable)
          GO_VERSION=1.26.1   # Update as needed
          wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz -O /tmp/go.tar.gz
          tar -C /usr/local -xzf /tmp/go.tar.gz
          rm /tmp/go.tar.gz

          echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
          source /etc/profile

      - name: "Add go binaries to Path"
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Ensure Task Runner is installed
        run: go install github.com/magefile/mage@latest

      - name: Install Tools
        working-directory: ./curious-ape
        run: mage tools

      - name: Prepare Database
        working-directory: ./curious-ape
        run: "mkdir -p ./tmp && mage migrate:up"

      - name: Generate Database Models
        working-directory: ./curious-ape
        run: mage db:gen

      - name: Test
        working-directory: ./curious-ape
        run: mage test

      - name: Audit
        working-directory: ./curious-ape
        run: mage audit
