name: Deploy
on:
  workflow_run:
    workflows: ["Test and Audit"]
    types: [completed]

env:
  AGE_KEY: /var/lib/act_runner/.age.txt
jobs:
  deploy:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    runs-on: arch-linux
    steps:
      - name: Clone Repository
        run: "git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY > /dev/null 2>&1"

      - name: "Add go binaries to Path"
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Deploy
        run: mage deploy
