name: Test and Audit
on: [push]

jobs:
  text-and-audit:
    runs-on: arch-linux
    steps:
      - name: Clone Repository
        run: "git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

      - run: "ls -la && pwd"
