name: Test and Audit
on: [push]

jobs:
  test-and-audit:
    runs-on: arch-linux
    steps:
      - name: Clone Repository
        run: "git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY > /dev/null 2>&1"

      - name: "Add go binaries to Path"
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Ensure Task Runner is installed
        run: go install github.com/magefile/mage@latest

      - name: Install Tools
        working-directory: ./curious-ape
        run: mage tools

      - name: Prepare Database
        working-directory: ./curious-ape
        run: "mkdir -p ./tmp && mage migrate:up"

      - name: Generate Database Models
        working-directory: ./curious-ape
        run: mage db:gen

      - name: Test
        working-directory: ./curious-ape
        run: mage test

      - name: Audit
        working-directory: ./curious-ape
        run: mage audit
