// Code generated by BobGen sqlite v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseDayMods DayModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewDay(mods ...DayMod) *DayTemplate {
	o := &DayTemplate{f: f}

	if f != nil {
		f.baseDayMods.Apply(o)
	}

	DayModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseDayMods() {
	f.baseDayMods = nil
}

func (f *Factory) AddBaseDayMod(mods ...DayMod) {
	f.baseDayMods = append(f.baseDayMods, mods...)
}
