apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: curious-ape-route
spec:
  parentRefs:
    - name: cilium-gateway-http
  hostnames:
    - "ape.danicos.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: curious-ape
          port: 4000
