apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curious-ape
  name: curious-ape
  namespace: curious-ape
spec:
  selector:
    matchLabels:
      app: curious-ape
  strategy: {}
  template:
    metadata:
      labels:
        app: curious-ape
    spec:
      containers:
      - env:
        - name: APE_ENVIRONMENT
          value: prod
        image: danicos.dev/daniel/curious-ape:2.0.2
        name: curious-ape
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /app/config.json
          name: config
          subPath: config.json
        - mountPath: /app/.env
          name: env-vol
          subPath: env
        - mountPath: /app/db-data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: curious-ape-pvc
      - name: config
        secret:
          items:
          - key: config.json
            path: config.json
          secretName: curious-ape-secret
      - name: litestream-vol
        secret:
          items:
          - key: litestream.yml
            path: litestream.yml
          secretName: curious-ape-secret
      - name: env-vol
        secret:
          items:
          - key: env
            path: env
          secretName: curious-ape-secret
status: {}
