#!/usr/bin/env fish

echo 'Tidying and verifying module dependencies...'
go mod tidy
go mod verify
go fmt ./...
echo 'Vetting code...'
go vet ./...
staticcheck -checks '"all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"' ./...
