application:
  port: 4444
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "ape"
  require_ssl: false
fitbit:
    provider: "fitbit"
    redirect_url: "http://localhost:4444/api/oauth2/fitbit/success"
    client_id: ""
    client_secret: ""
    authorization_uri: "https://www.fitbit.com/oauth2/authorize"
    access_token_uri: "https://api.fitbit.com/oauth2/token"
